const template = {
  utkarsh: {
    name: "",
    email: "",
    bitsId: "",
    codechef: "",
    codeforces: "",
    atcoder: "",
    hackerearth: "",
    hackerrank: "",
  },
};

export const memberList = [
  {
    name: "Yashdeep Gupta",
    email: "f20170114@pilani.bits-pilani.ac.in",
    bitsId: "2017A7PS0114P",
    codechef: "codechef.com/users/yashdeepgupta",
    codeforces: "",
    atcoder: "",
    hackerearth: "",
    hackerrank: "",
  },
  {
    name: "Aakash Gupta",
    email: "f20180887@pilani.bits-pilani.ac.in",
    bitsId: "2018B4A70887P",
    codechef: "https://www.codechef.com/users/aakashbitspila/",
    codeforces: "https://codeforces.com/profile/AakashBitsPilani",
    atcoder: "https://atcoder.jp/users/AakashBitsPilani",
    hackerearth: "https://www.hackerearth.com/@aakash554",
    hackerrank: "https://www.hackerrank.com/f201808871",
  },
  {
    name: "Utkarsh",
    email: "f20200981@pilani.bits-pilani.ac.in",
    bitsId: "2020A7PS0981P",
    codechef: "https://www.codechef.com/users/utkarsh_utk",
    codeforces: "https://codeforces.com/profile/Utkarsh-UTK",
    atcoder: "",
    hackerearth: "",
    hackerrank: "",
  },
  {
    name: "Yogesh Gupta",
    email: "f20190435@pilani.bits-pilani.ac.in",
    bitsId: "2019A8PS0435P",
    codechef: "https://www.codechef.com/users/yogeshguptakai",
    codeforces: "https://codeforces.com/profile/codeghost_2001",
    atcoder: "",
    hackerearth: "",
    hackerrank: "https://www.hackerrank.com/noobie_2001",
  },
  {
    name: "Aniket Jain",
    email: "f20190037@pilani.bits-pilani.ac.in",
    bitsId: "2019A7PS0037P",
    codechef: "https://www.codechef.com/users/aniketjain0317",
    codeforces: "https://codeforces.com/profile/aniketjain0317",
    atcoder: "",
    hackerearth: "",
    hackerrank: "",
  },
  {
    name: "Shivansh Agarwal",
    email: "f20200774@pilani.bits-pilani.ac.in",
    bitsId: "2020B3PS0774P",
    codechef: "https://www.codechef.com/users/shivansh0809",
    codeforces: "https://codeforces.com/profile/Shivansh0809",
    atcoder: "",
    hackerearth: "",
    hackerrank: "https://www.hackerrank.com/shivanshagrawal3",
  },
  {
    name: "Tanveer Singh",
    email: "f20200084@pilani.bits-pilani.ac.in",
    bitsId: "2020A7PS0084P",
    codechef: "https://www.codechef.com/users/brobat",
    codeforces: "https://codeforces.com/profile/brobat",
    atcoder: "",
    hackerearth: "",
    hackerrank: "",
  },
  {
    name: "Anish Kasegaonkar",
    email: "f20200785@pilani.bits-pilani.ac.in",
    bitsId: "2020B3PS0785P",
    codechef: "https://www.codechef.com/users/anish_ak",
    codeforces: "https://codeforces.com/profile/Anish_aak",
    atcoder: "",
    hackerearth: "",
    hackerrank: "https://www.hackerrank.com/anishkgkar",
  },
  {
    name: "Mridul Chandak",
    email: "f20200133@pilani.bits-pilani.ac.in",
    bitsId: "2020A7PS0133P",
    codechef: "https://www.codechef.com/users/meriddle",
    codeforces: "https://codeforces.com/profile/MeRiddle",
    atcoder: "",
    hackerearth: "",
    hackerrank: "",
  },
  {
    name: "Siddharth Sharma ",
    email: "f20190064@pilani.bits-pilani.ac.in",
    bitsId: "2019A7PS0064P",
    codechef: "https://www.codechef.com/users/angrybird144",
    codeforces: "https://codeforces.com/profile/AngryBird144",
    atcoder: "",
    hackerearth: "",
    hackerrank: "",
  },
  {
    name: "Chinmay Shah",
    email: "f20190032@pilani.bits-pilani.ac.in",
    bitsId: "2019A7PS0032P",
    codechef: "https://www.codechef.com/users/cjshah2000",
    codeforces: "https://codeforces.com/profile/nimblerockstar",
    atcoder: "",
    hackerearth: "",
    hackerrank: "",
  },
  {
    name: "Kalash Shah",
    email: "f20180213@pilani.bits-pilani.ac.in ",
    bitsId: "2018A7PS0213P ",
    codechef: "https://www.codechef.com/users/kalashshah11",
    codeforces: "https://codeforces.com/profile/Hypersomniac",
    atcoder: "",
    hackerearth: "",
    hackerrank: "",
  },
  {
    name: "Niket Agarwal",
    email: "f20190378@pilani.bits-pilani.ac.in",
    bitsId: "2019A8PS0378P",
    codechef: "https://www.codechef.com/users/main_hoon_don",
    codeforces: "https://codeforces.com/profile/main_hoon_don",
    atcoder: "",
    hackerearth: "",
    hackerrank: "",
  },
  {
    name: "Hemant Agarwal",
    email: "f20200706@pilani.bits-pilani.ac.in",
    bitsId: "2020A1PS0706P",
    codechef: "https://www.codechef.com/users/agarwalhemant",
    codeforces: "https://codeforces.com/profile/agarwalhemant",
    atcoder: "",
    hackerearth: "",
    hackerrank: "",
  },
  {
    name: "Ashish Pathak",
    email: "f20180048@pilani.bits-pilani.ac.in",
    bitsId: "2018B3A30048P",
    codechef: "https://www.codechef.com/users/ashishpathak28",
    codeforces: "https://codeforces.com/profile/MastAadmiAshish",
    atcoder: "",
    hackerearth: "",
    hackerrank: "",
  },
  {
    name: "Tanish Bansal",
    email: "f20190356@pilani.bits-pilani.ac.in",
    bitsId: "2019A8PS0356P",
    codechef: "https://www.codechef.com/users/ab_9102",
    codeforces: "http://codeforces.com/profile/bansaltanish149",
    atcoder: "",
    hackerearth: "",
    hackerrank: "",
  }
];
